servo: Merge #19362 - Enable pip error output in mach_bootstrap.py (from SWW13:pip_log); r=jdm
When `pip` encounters an error during mach bootstrapping in `mach_bootstrap.py` there is no error log because of `-q`. The output will only be read when an error was encountered, so this looks like an unintended mistake.

---

This gives error outputs like:
```
D:\Code\moz\servo>mach.bat -h
Pip failed to execute properly:
Output: Collecting marionette_driver>=2.4 (from -r D:\Code\moz\servo\tests\wpt\web-platform-tests\tools\wptrunner\requirements_firefox.txt (line 1))
  Using cached marionette_driver-2.4.0.tar.gz
Collecting mozprofile>=0.21 (from -r D:\Code\moz\servo\tests\wpt\web-platform-tests\tools\wptrunner\requirements_firefox.txt (line 2))
  Using cached mozprofile-0.28.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\$USER\AppData\Local\Temp\pip-build-zqivz5en\mozprofile\setup.py", line 12, in <module>
        assert sys.version_info[0] == 2
    AssertionError

    ----------------------------------------

Error: Command "python setup.py egg_info" failed with error code 1 in C:\Users\$USER\AppData\Local\Temp\pip-build-zqivz5en\mozprofile\
```

instead of:

```
D:\Code\moz\servo>mach.bat -h
Pip failed to execute properly:
Output:
Error: Command "python setup.py egg_info" failed with error code 1 in C:\Users\$USER\AppData\Local\Temp\pip-build-htd5no9k\mozprofile\
```

Source-Repo: https://github.com/servo/servo
Source-Revision: b5b24559254f265a6783c3e91a833d51319dccfa