Bug 1516363: Fix duplicate definition of scoreThreshold causing compile error with `--disable-tests` r=gcp
When compiling without ENABLE_TESTS, the following error occurs:

/toolkit/xre/ModuleEvaluator_windows.cpp(221,20):  error: redefinition of
    'scoreThreshold' with a different type: 'const int' vs 'int'

This removes the 2 lines of code that caused the error.

Differential Revision: https://phabricator.services.mozilla.com/D15372